### PR TITLE
Update TUTORIAL.md with typo fixed 

### PR DESCRIPTION
**Pull request by ElbinBinil**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/44962

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contributing.

**Comment by ElbinBinil** [comment]
> This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.
> 
> Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
> 
> Happy contributing.

Hey I am new to open source and I read all your docs regarding contribution but what is the mistake here

**Comment by gikf** [comment]
Making change to the `TUTORIAL.md` file is part of what is needed to update tutorial. What is still required truly is written on the page I've linked above.

**Comment by moT01** [comment]
Thanks for the PR @ElbinBinil. This was fixed by another one so it's safe to close - thanks and happy coding 🎉

**Pull request closed without merging**
