### PR TITLE
Fixed typos and errors which I encountered while going through the tutorial

### PR DESCRIPTION
**Pull request by Raj-Pansuriya**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes no issue

The changes I made fixes typos and a couple of syntax errors given in the hints of questions. The changes are small, but can mislead beginners if kept as it is so I thought to submit a PR

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contributing.

**Comment by Raj-Pansuriya** [comment]
Thanks for the guiding link @gikf . I did read the freeCodeCamp contributing guidlines but did not know anything specific to contribute to CodeRoad tutorials.

So now, along with these changes, I need to have 1 more commit `update json` after running `coderoad build` which holds for jason file changed due to previous fixes. Am I right or I still didn't get you? Please Confirm😅

**Comment by gikf** [comment]
@Raj-Pansuriya yes, that's correct.

**Comment by Raj-Pansuriya** [comment]
ok thanks! Also this is my first contribution to any CodeRoad tutorial, so I do not have CodeRoad CLI tools installed on my machine. I did above chages directly from GitHub.

My question is, Can we install those tools in a specific environment like we do in Python or should I install them globally on my system?

**Comment by gikf** [comment]
I know it can be installed globally with `npm install -g @coderoad/cli`, installing it per tutorial might not be too convenient.

**Comment by Raj-Pansuriya** [comment]
Ok will proceed accordingly then. Thanks again for being so patient with me 😅😅

Will revert back with necessary changes ASAP

**Comment by Raj-Pansuriya** [comment]
As you said, I tried bulding the repo with `coderoad` but got below error
image
I asked about it on the fCC chat but got no solution.

Today after a PR from @moT01 I was able to understand the problem and proceeded further. There were some merge confilicts which I didin't know how to resolve. So I have opened another PR ( #8 ) along with the requested changes.

Not a good practice, but I really didn't know what to do! Sorry...

**Comment by moT01** [comment]
Hey @Raj-Pansuriya - sorry, I missed your message in chat. CodeRoad and the CLI tools got an update recently, like the last few days. Tutorials now require an id - and optionally, some other config. I pushed the id's to all the tutorials a few days ago. So you would need to pull in the new changes that include the id. Then, that command should work for you - hopefully.

**Comment by Raj-Pansuriya** [comment]
No worries at all, @moT01. I am just happy that the solution is now available. I have 3 tuts cloned right now and they are working just fine. Thanks for the help!!😀

**Pull request closed without merging**
