### PR TITLE
fix: corrected typos and errors

### PR DESCRIPTION
**Pull request by Raj-Pansuriya**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #5

The changes I made fixes typos and a couple of syntax errors given in the hints of questions. The changes are small, but can mislead beginners if kept as it is so I thought to submit a PR

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
I can't use github to make suggestion on these lines, but there's two more cases with _ispsum_ spelling - titles of 420 and 860 steps.

https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator/blob/3f2bf19286b240be303e97463502841245142390/TUTORIAL.md?plain=1#L565

https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator/blob/3f2bf19286b240be303e97463502841245142390/TUTORIAL.md?plain=1#L1136

**Comment by Raj-Pansuriya** [comment]
Done

**Review by gikf — APPROVED** [review]
Looks good to me :+1: 

Thanks for corrections.

**Comment by Raj-Pansuriya** [comment]
Was happy to contribute!😄

**Pull request merged**
